### ISSUE TITLE
Transfer this repository to the organization?

### ISSUE THREAD

**Issue by jacebrowning** [tlwt/doorstop-docker#1]
https://github.com/doorstop-dev was created to collaborate on all Doorstop projects. Would you like to transfer this repository to us for more visibility?

This can be done using the "Transfer" button on https://github.com/tlwt/doorstop-docker/settings.

We'll also want to update this link: https://doorstop.readthedocs.io/en/latest/examples/

**Comment by tlwt** [comment]
Hi Jace,

just tried and got the error that I am not allowed to create repositories. You might need to assign those rights temporarily to me. 

Cheers, Till





Till S. Witt
Colmarer Str. 6, 28211 Bremen
+49 (173) 99 136 13
mail@tillwitt.de

**Comment by jacebrowning** [comment]
@tlwt I just added you as a [member](https://github.com/orgs/doorstop-dev/people), which should grant you permission to create repositories.
